name: Secure File Uploader
on:
  repository_dispatch:
    types: [upload-room, upload-avatar]

jobs:
  commit-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Create File
        run: |
          mkdir -p registry
          echo "${{ github.event.client_payload.content }}" | base64 -d > registry/${{ github.event.client_payload.filename }}
      - name: Commit and Push
        run: |
          git config user.name "Museum Bot"
          git config user.email "bot@users.noreply.github.com"
          git add registry/
          git commit -m "Auto-add: ${{ github.event.client_payload.filename }}"
          git push
